# Sowing Success: How Machine Learning Helps Farmers Select the Best Crops

![Farmer in a field](farmer_in_a_field.jpg)

Measuring essential soil metrics such as nitrogen, phosphorous, potassium levels, and pH value is an important aspect of assessing soil condition. However, it can be an expensive and time-consuming process, which can cause farmers to prioritize which metrics to measure based on their budget constraints.

Farmers have various options when it comes to deciding which crop to plant each season. Their primary objective is to maximize the yield of their crops, taking into account different factors. One crucial factor that affects crop growth is the condition of the soil in the field, which can be assessed by measuring basic elements such as nitrogen and potassium levels. Each crop has an ideal soil condition that ensures optimal growth and maximum yield.

A farmer reached out to you as a machine learning expert for assistance in selecting the best crop for his field. They've provided you with a dataset called `soil_measures.csv`, which contains:

- `"N"`: Nitrogen content ratio in the soil
- `"P"`: Phosphorous content ratio in the soil
- `"K"`: Potassium content ratio in the soil
- `"pH"` value of the soil
- `"crop"`: categorical values that contain various crops (target variable).

Each row in this dataset represents various measures of the soil in a particular field. Based on these measurements, the crop specified in the `"crop"` column is the optimal choice for that field.  

In this project, you will build multi-class classification models to predict the type of `"crop"` and identify the single most importance feature for predictive performance.

In [42]:
# All required libraries are imported here for you.
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score

# Load the dataset
crops = pd.read_csv("soil_measures.csv")

# Write your code here
crops.head()

N   P   K        ph  crop
0  90  42  43  6.502985  rice
1  85  58  41  7.038096  rice
2  60  55  44  7.840207  rice
3  74  35  40  6.980401  rice
4  78  42  42  7.628473  rice

In [25]:
crops.shape

(2200, 5)

In [26]:
crops.describe()

N            P            K           ph
count  2200.000000  2200.000000  2200.000000  2200.000000
mean     50.551818    53.362727    48.149091     6.469480
std      36.917334    32.985883    50.647931     0.773938
min       0.000000     5.000000     5.000000     3.504752
25%      21.000000    28.000000    20.000000     5.971693
50%      37.000000    51.000000    32.000000     6.425045
75%      84.250000    68.000000    49.000000     6.923643
max     140.000000   145.000000   205.000000     9.935091

In [27]:
crops.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   N       2200 non-null   int64  
 1   P       2200 non-null   int64  
 2   K       2200 non-null   int64  
 3   ph      2200 non-null   float64
 4   crop    2200 non-null   object 
dtypes: float64(1), int64(3), object(1)
memory usage: 86.1+ KB


In [28]:
crops.isna().sum()

N       0
P       0
K       0
ph      0
crop    0
dtype: int64

In [29]:
X = crops.drop('crop', axis=1)
y = crops.crop

In [30]:
print(f'The shape of X is: {X.shape}')
print(f'The shape of y is: {y.shape}')

The shape of X is: (2200, 4)
The shape of y is: (2200,)


In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [32]:
print(f'The size of X_train is {X_train.shape}, and the shape of X_test is {X_test.shape}')

The size of X_train is (1760, 4), and the shape of X_test is (440, 4)


In [33]:
scaler = StandardScaler()

In [34]:
logreg = LogisticRegression(multi_class="multinomial")

In [35]:
steps = [
    ('scaler', scaler),
    ('logreg', logreg)
]

pipeline = Pipeline(steps=steps)

In [36]:
pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)

In [37]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       apple       0.88      0.30      0.45        23
      banana       1.00      1.00      1.00        21
   blackgram       0.76      0.65      0.70        20
    chickpea       1.00      0.77      0.87        26
     coconut       0.81      0.63      0.71        27
      coffee       0.76      0.76      0.76        17
      cotton       0.88      0.88      0.88        17
      grapes       0.45      0.93      0.60        14
        jute       0.50      0.48      0.49        23
 kidneybeans       0.45      0.65      0.53        20
      lentil       0.30      0.64      0.41        11
       maize       0.91      1.00      0.95        21
       mango       0.40      0.53      0.45        19
   mothbeans       0.60      0.25      0.35        24
    mungbean       0.67      0.74      0.70        19
   muskmelon       0.62      0.76      0.68        17
      orange       1.00      1.00      1.00        14
      papaya       0.74    

In [38]:
print(confusion_matrix(y_test, y_pred))

[[ 7  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 13  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0 17  0  0  0  0  0  0  0  5  0  0  0  0  0  0  5  0  0]
 [ 0  0  0  0  0 13  2  0  0  0  0  1  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  1 15  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0 13  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  0  0 11  0  0  0  0  0  0  0  0  1  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 13  0  0  0  0  1  0  0  0  6  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  3  0  0  0  0  0  0  0 10  1  1  0  0  0  0  4  0  0]
 [ 0  0  1  0  0  0  0  0  0  3  2  0  8  6  4  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  1

In [39]:
params = {"logreg__solver": ["newton-cg", "saga", "lbfgs"],
         "logreg__C": np.linspace(0.001, 1.0, 10)}

# Create the GridSearchCV object
tuning = GridSearchCV(pipeline, param_grid=params)
tuning.fit(X_train, y_train)
y_pred = tuning.predict(X_test)

# Compute and print performance
print("Tuned Logistic Regression Parameters: {}, Accuracy: {}".format(tuning.best_params_, tuning.score(X_test, y_test)))

Tuned Logistic Regression Parameters: {'logreg__C': 1.0, 'logreg__solver': 'lbfgs'}, Accuracy: 0.6590909090909091


In [44]:
best_feature = None
best_score = 0.0

# Loop through each feature and evaluate performance
for feature in X:
    X = crops[[feature]]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

    steps = [('scaler', StandardScaler()), ('logreg', LogisticRegression())]

    pipeline = Pipeline(steps=steps)

    pipeline.fit(X_train, y_train)
    y_pred = pipeline.predict(X_test)

    score = accuracy_score(y_test, y_pred)

    if score > best_score:
        best_score = score
        best_feature = feature

# Store the result in a dictionary
best_predictive_feature = {best_feature: best_score}

print("Best predictive feature:", best_predictive_feature)


Best predictive feature: {'ph': 0.11212121212121212}
